apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: ticketing-platform
  labels:
    app: ticket-service
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
        tier: application
    spec:
      containers:
        - name: ticket-service
          image: ticketing/ticket-service:latest
          ports:
            - containerPort: 3006
          envFrom:
            - configMapRef:
                name: ticketing-platform-config
            - secretRef:
                name: ticketing-platform-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
