/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ShowtimesIdRouteImport } from './routes/showtimes.$id'
import { Route as MoviesIdRouteImport } from './routes/movies.$id'
import { Route as CheckoutRidRouteImport } from './routes/checkout.$rid'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowtimesIdRoute = ShowtimesIdRouteImport.update({
  id: '/showtimes/$id',
  path: '/showtimes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRidRoute = CheckoutRidRouteImport.update({
  id: '/checkout/$rid',
  path: '/checkout/$rid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tickets': typeof MyTicketsRoute
  '/staff': typeof StaffRoute
  '/checkout/$rid': typeof CheckoutRidRoute
  '/movies/$id': typeof MoviesIdRoute
  '/showtimes/$id': typeof ShowtimesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tickets': typeof MyTicketsRoute
  '/staff': typeof StaffRoute
  '/checkout/$rid': typeof CheckoutRidRoute
  '/movies/$id': typeof MoviesIdRoute
  '/showtimes/$id': typeof ShowtimesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/movies': typeof MoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tickets': typeof MyTicketsRoute
  '/staff': typeof StaffRoute
  '/checkout/$rid': typeof CheckoutRidRoute
  '/movies/$id': typeof MoviesIdRoute
  '/showtimes/$id': typeof ShowtimesIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/manager'
    | '/my-tickets'
    | '/staff'
    | '/checkout/$rid'
    | '/movies/$id'
    | '/showtimes/$id'
    | '/tickets/$id'
    | '/movies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/manager'
    | '/my-tickets'
    | '/staff'
    | '/checkout/$rid'
    | '/movies/$id'
    | '/showtimes/$id'
    | '/tickets/$id'
    | '/movies'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/manager'
    | '/my-tickets'
    | '/staff'
    | '/checkout/$rid'
    | '/movies/$id'
    | '/showtimes/$id'
    | '/tickets/$id'
    | '/movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  MyTicketsRoute: typeof MyTicketsRoute
  StaffRoute: typeof StaffRoute
  CheckoutRidRoute: typeof CheckoutRidRoute
  MoviesIdRoute: typeof MoviesIdRoute
  ShowtimesIdRoute: typeof ShowtimesIdRoute
  TicketsIdRoute: typeof TicketsIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showtimes/$id': {
      id: '/showtimes/$id'
      path: '/showtimes/$id'
      fullPath: '/showtimes/$id'
      preLoaderRoute: typeof ShowtimesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$rid': {
      id: '/checkout/$rid'
      path: '/checkout/$rid'
      fullPath: '/checkout/$rid'
      preLoaderRoute: typeof CheckoutRidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  MyTicketsRoute: MyTicketsRoute,
  StaffRoute: StaffRoute,
  CheckoutRidRoute: CheckoutRidRoute,
  MoviesIdRoute: MoviesIdRoute,
  ShowtimesIdRoute: ShowtimesIdRoute,
  TicketsIdRoute: TicketsIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
